### ISSUE TITLE
Uncaught TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by Christilut** [gurghet/vue-smart-table#21]
```html
<smart-table
    :auto-load="true"
    body-path="results"
    id-col="id.value"
    endpoint="http://api.randomuser.me/?results=20"
    :order-by="['name.first', 'name.last']"

    ></smart-table>
```

Getting this stacktrace when using any value in endpoint. Above snippet is copy pasted from readme.

```
Uncaught TypeError: Cannot read property 'get' of undefined
refresh @ SmartTable.vue?c608:409
(anonymous function) @ vue.common.js?e881:216
compiled @ SmartTable.vue?c608:345
Vue._callHook @ vue.common.js?e881:8235
Vue._compile @ vue.common.js?e881:8628
Vue.$mount @ vue.common.js?e881:9446
Vue._init @ vue.common.js?e881:2468
Vue._init @ vue-router.js?e71f:1756
SmartTable @ VM47638:2
```

Using Vue 1.0.26, installed SmartTable with NPM and using webpack.

**Comment by gurghet** [comment]
Have you installed vue-resource?

**Comment by Christilut** [comment]
Yes it is installed under `node_modules`

**Comment by gurghet** [comment]
Which version?

**Comment by Christilut** [comment]
0.9.3

**Comment by gurghet** [comment]
Thanks for the heads up, I will look into the problem tonight.

**Comment by gurghet** [comment]
The line that is giving you the error is

    this.$http.get(this.endpoint)

in particular the `$http` is undefined, this means you haven't installed `vue-resource` properly.
Maybe you didn't write `Vue.use(VueResource)`?

**Comment by Christilut** [comment]
Yep adding `Vue.use(VueResource)` fixed it. I didn't know that was a requirement, don't see it anywhere in the readme either. 
Thanks for the quick help, keep up the good work :)

**Comment by gurghet** [comment]
I didn't think about adding it because it's VueResource's documentation, not mine. But now it's pretty stable and I may add it as well.
