### ISSUE TITLE
Is there a way to use a dropdown component inside of the smart-table?

### ISSUE THREAD

**Issue by lavezzi1** [gurghet/vue-smart-table#23]
Hello Andrea!

I wanna use dropdown component (like this for example https://github.com/JosephusPaye/Keen-UI/blob/master/src/UiMenu.vue it gets an array for options) inside of the table for each entry. And option might be 'View', 'Delete' etc. Its works fine when you need just static option, but in my case I need unique id for each entry in the table. 

```
<smart-table
    body="dataTable"
    >
   <ui-menu :list="$parent.dataTable.dropdown"></ui-menu>
  </smart-table>
```

```
        var dataTable = [
                {
                    img: '',
                    name: '',
                    region: '',
                    dropdown: [
                        {
                            id: '',
                            text: '',
                            url: ''
                        }
                    ]
                },
            {% endfor %}
        ];
```

So it doesn't works. Only works if I type something like `<ui-menu :list="$parent.dataTable[0].dropdown"></ui-menu>` but of course it isn't solution because the id will the same for all entries. But I want to itterate them. 

Please, provide some example of can I do that maybe with another dropdown component or even with basic select. Thanks you so much!

**Comment by gurghet** [comment]
It's now clear what you want to achieve here. If you want to iterate the `dropdown` objects of the `dataTable` object you should create a new array with the array you really want to iterate and then pass it as a prop in the list.

    let dataTableDropdowns = [].concat(...dataTable.map(d => d.dropdown))

**Comment by lavezzi1** [comment]
Is that right?

```
        var dataTable = [
            {% for item in item_list %}
                {
                    img: '',
                    name: '',
                    region: '',
                    dropdown: []
                },
            {% endfor %}
        ];
        let dataTableDropdowns = [
           {% for item in item_list %}
              {
                    id: "{{ forloop.id }}",
                    text: "",
                    url: "{% url 'item_url' item.id %}"
              },
           {% endfor %}
        ].concat(...dataTable.map(d => d.dropdown));
```

**Comment by gurghet** [comment]
Nope, `[]` is an empty array

**Comment by lavezzi1** [comment]
```
        :list="$parent.dataTableDropdowns"

        var dataTable = [
            {% for item in item_list %}
                {
                    img: '',
                    name: '',
                    region: '',
                    dropdown: [
                           {
                                id: "{{ forloop.id }}",
                                text: "text",
                                url: "{% url 'item_url' item.id %}"
                           }
                    ]
                },
            {% endfor %}
        ];
        let dataTableDropdowns = [].concat(...dataTable.map(d => d.dropdown));
```

I got two option in dropdown from two entries. I mean I got two entries id: 1 and id: 2 so I expect to see one option in the dropdown for the first entry with id: 1 and for the second id: 2 but I have both option in each dropdown. What's wrong ?

**Comment by gurghet** [comment]
Oh ok, I know what you mean. So you don't need `dataTableDropdowns`, just create something like

    <ui-menu :list="$parent.dataTable[i].dropdown" v-for="(v, i) in $parent.dataTable"></ui-menu>

**Comment by lavezzi1** [comment]
What is v in (v, i)?

Got this error
```
$parent.dataTable[i].dropdown": TypeError: Cannot read property 'undefined' of undefined
```

**Comment by gurghet** [comment]
Sorry I was conflating with Vue2.0: use `v in $parent.dataTable` and
`v.dropdown`

пн, 3 окт. 2016 г. в 16:57, lavezzi1 <notifications@github.com>:

**Comment by lavezzi1** [comment]
Can you completely write this line?

**Comment by gurghet** [comment]
I'm on the go, will write later

пн, 3 окт. 2016 г. в 17:02, lavezzi1 <notifications@github.com>:

**Comment by lavezzi1** [comment]
Ok thanks.

**Comment by lavezzi1** [comment]
How will it look like? I tried all :/

**Comment by lavezzi1** [comment]
@gurghet Andrea, please, write this line

**Comment by lavezzi1** [comment]
No way to get answer? Please 🙏🏿

**Comment by gurghet** [comment]
I'll answer tomorrow

**Comment by gurghet** [comment]
<ui-menu :list="v.dropdown" v-for="v in $parent.dataTable"></ui-menu>

**Comment by lavezzi1** [comment]
@gurghet I tested it and seems like it works but I don't see actual dropdown, just text '	
[object Object]'

If I do `dataTable[0].dropdown`
I got id text and url which is absolutely correct. But why I get text?
