### ISSUE TITLE
Babel language tag

### ISSUE THREAD

**Issue by janat08** [gurghet/vue-smart-table#25]
The dependency for making http requests or something hasn't installed when I called meteor npm install, but now it's complaining that I also don't have handler for babel tag.

**Comment by gurghet** [comment]
Can you elaborate?

**Comment by janat08** [comment]
From memory there's a component that has html lang tag for babel in a core module or something, yet it doesn't appear to be listed as dependency unless its a dependency of some npm package for using external sources which choose to not install on my repo for some reason.

**Comment by janat08** [comment]
I get a warning after starting up server that warns that it doesn't
understand what I imagine goes as <template babel> or <script babel>. I'll
get back at you later with the actual message from terminal.

**Comment by janat08** [comment]
Im running vue through a wrapper, author of which also offers these handlers for HTML, so I suppose even if the handler is included in your package it would warn regardless.
`
[vue-component] Error while compiling in tag <script> using lang babel: Can't find handler for lang babel, did you install it? -> in node_modules/vue-smart-table/src/components/AsyncImg.vue at line 12
[vue-component] Error while compiling in tag <script> using lang babel -> in node_modules/vue-smart-table/src/components/AsyncImg.vue at line 12
{ [Error: [vue-component] Error while compiling in tag <script> using lang babel: Can't find handler for lang babel, did you install it?] line: 12 }
`

**Comment by gurghet** [comment]
I'm sorry, I'm afraid I can't help you. Anyways, it seems that your error is not related to Smart Table. I'm going to close this issue for now, but please feel free to add details. Maybe someone else will be able to help you.
