### ISSUE TITLE
Interpolation inside attributes has been removed

### ISSUE THREAD

**Issue by vote539** [gurghet/vue-smart-table#28]
When I try to run the Hello World example from the readme file, I get this error in the console:

> `[Vue warn]: class="col-{{col.key}} col-cell {{canOrderBy(col.key) ? 'ord' : ''}} {{orderClass(col.key)}}": Interpolation inside attributes has been removed. Use v-bind or the colon shorthand instead. For example, instead of <div class="{{ val }}">, use <div :class="val">. `

My package.json has:

    "vue": "^2.0.5",
    "vue-router": "^2.0.1",
    "vue-smart-table": "^2.6.0-beta5"

Any ideas on how to avoid this error and run the Hello World example?  Thanks.

**Comment by gurghet** [comment]
Hi vote539, vue-smart-table is not compatible with Vue 2.0 I'm currently busy with other projects.
