### ISSUE TITLE
Doesn't work in IE11

### ISSUE THREAD

**Issue by lavezzi1** [gurghet/vue-smart-table#5]
Hi, I want to support IE11 but it seems like this component doesn't. I got this error in the console of IE11

>Object doesn't support property or method 'find'

`var row = father.processedSmartBody.find(byId(id));`

I didn't find a solution. If you know how to fix it, share please.

**Comment by gurghet** [comment]
I don't currently plan to support IE, but I added the find polyfill anyways since it's needed by Chrome for Android. It should work now in both browsers.
