### ISSUE TITLE
Browserify error

### ISSUE THREAD

**Issue by jackmcdade** [gurghet/vue-smart-table#6]
As soon as i try to require it, i get this:

```
Browserify Failed!: Unexpected token

/public/node_modules/vue-smart-table/src/components/SmartTable.vue:1
<template>
^
ParseError: Unexpected token
```

**Comment by jackmcdade** [comment]
I'm not convinced this is on your side though. I'm using Vueify and Laravel Elixir. It could be something about requiring a third-party Vueify component.

**Comment by gurghet** [comment]
I'm not familiar with this particular toolchain but I suspect vueify is not loaded correctly because the error appears to be the `<template>` tag.
If I understand correctly Vueify should be in charge of parsing the .vue files. Do you have other .vue files that parse correctly?

**Comment by jackmcdade** [comment]
I do, but they're not `npm` dependencies. They're all local.
Snippet: 
```
// Vueify Objects (these work)
import Modal from './components/Modal.vue'
import FlashMessage from './components/FlashMessage.vue'
...
// Yours (doesn't work)
import SmartTable from 'vue-smart-table'
```

**Comment by gurghet** [comment]
`import SmartTable from 'vue-smart-table'` points to `scr/components/SmartTable.vue`. It maybe something wrong with the Vueify configuration. Can you check with other components? Like vue-strap?

**Comment by gurghet** [comment]
I will close this issue, for now, feel free to share what you discovered even if it was not related to my component.
